### ISSUE TITLE
Probleme mit Mac OS

### ISSUE THREAD

**Issue by PaulSchwanitz** [ManeLippert/AssemblerVSCode#1]
Bei mir funktioniert des nicht unter MAC OS😭

**Comment by ManeLippert** [comment]
Unter MacOS ist pk2cmd nur bis zur Version 10.4 (Tiger) und 10.5 (Leopard) unterstützt. Womit der Support schon mit BigSur (MacOS 11) eingestellt worden ist. Leider ist auch noch keine neue Version von pk2cmd veröffentlicht worden, was die aktuellste Version 1.20 bleiben wird. 
(Quelle: https://github.com/psmay/pk2cmd/blob/master/pk2cmd/Readme%20For%20PK2CMD%20MacOSX.txt)
